spring:
  application:
    name: MicroServer1

server:
  port: 7111

host:
  name: localhost


eureka:
  password: password
  client:
    serviceUrl:
 #     defaultZone: http://user:${eureka.password}@msdemo:8761/eureka/
       defaultZone: http://user:${eureka.password}@${host.name}:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
